config/routes.rb
Rails.application.routes.draw do
  root to: 'customers#index' 
  resources :customers
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :phone,  presence: true
    validates :phone, numericality: { only_integer: true }
    validates :phone, length: { is: 10}    

    
    def full_name
        "#{first_name} #{last_name}"
    end
end










# validates :email, presence: true
# validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  validates_associated :customer
  validates_presence_of :customer
  validates :product_name, presence: true
  validates :product_count, presence: true
  validates :product_count, numericality: { 
    only_integer: true,  
    greater_than: 0
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  layout 'customer_layout'
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash.notice = "The customer record was created successfully."
      redirect_to @customer
    else
      flash.now.alert = @customer.errors.full_messages.to_sentence
      render :new  
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    if @customer.update(customer_params)
      flash.notice = "The customer record was updated successfully."
      redirect_to @customer
    else
      flash.now.alert = @customer.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to customers_path
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
    before_action :set_order, only: [:show, :edit, :update, :destroy]

    def index 
        @orders = Order.all 
    end

    def show 
    end

    def new 
        @order = Order.new 
    end

    def edit 
    end

    def create 
        @order = Order.new(order_params)
        if @order.save 
            flash.notice = "The order was created successfully"
            redirect_to @order 
        else
            flash.now.alert = @order.errors.full_messages.to_sentence 
            render :new 
        end
    end

    def update 
        if @order.update(order_params)
            flash.notice = "The order was updated successfully"
            redirect_to @order 
        else
            flash.now.alert = @order.errors.full_messages.to_sentence 
            render :edit 
        end
    end

    def destroy
        @order.destroy 
        respond_to do |format|
            format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params 
        params.require(:order).permit(:product_name, :product_count, :customer_id)
    end

    def catch_not_found(e)
        Rails.logger.debug("We had a not found exception")
        flash.alert = e.to_s
        redirect_to orders_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.full_name %></td>
        <td><%= customer.phone %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>
<br>
<br>
<%= link_to 'View Orders', orders_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Product Count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer.orders.each do |order| %>
      <tr>
        <td><%= order.product_name %></td>
        <td><%= order.product_count %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New order', new_order_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerOrder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/customer_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerOrder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if !flash[:alert].nil? %>
    <p class="my_alert"><%= flash[:alert] %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
    <% if order.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(order.errors.count, "error") %>prohibited this order from being saved</h2>

        <ul>
        <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
      <% end %>

    <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
    </div>

    <div class="field">
    <%= f.label :product_count %>
    <%= f.text_field :product_count %>
    </div>

    <%=
    f.select :customer_id, 
        options_for_select(Customer.all.map do |c|
        ["#{c.first_name} #{c.last_name}", c.id] 
        end
        )
    %>

    <div class="actions">
        <%= f.submit %>
    </div>

<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show Page', @order %> | 
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Product Count</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_name %></td>
        <td><%= order.product_count %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
<br>
<br>
<%= link_to 'View Customers', customers_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order%>

<%=link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @order.product_name %>
</p>

<p>
  <strong>Product Count:</strong>
  <%= @order.product_count %>
</p>

<p>
  <strong>Customer:</strong>
  <%=
    cc = Customer.find(@order.customer_id) 
    "#{cc.first_name} #{cc.last_name}" 
  %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>